product/rdkronos: Fix unaligned access to NCI nodes
The data structure of NCI like:
    struct {
        volatile uint32_t type:16;
        volatile uint32_t id:16;
    };
some compilers will generate 16-bit access to the NCI IO spaces.
This will cause FVP Error like:
  ERROR: RD_Kronos.css.io_macro_0.io_nci.RegisterInterface:
  read must be 32 bit aligned to offset 0x3f0108

Now we introduce a 32-bit union to force compiler generate 32-bits
access code these IO spaces by 32-bits.

Upstream-Status: Pending
Signed-off-by: Wei Chen <wei.chen@arm.com>